In [1]:
# STEP 1: Upload dataset
from google.colab import files
uploaded = files.upload()   # Select sensor_log.csv manually

# STEP 2: Load data
import pandas as pd
df = pd.read_csv("sensor_log.csv")  # filename only!
print("Original Data:")
display(df)

# STEP 3: Check missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# STEP 4: Create 4 different versions
# Forward Fill
df_forward_fill = df.fillna(method='ffill')

# Backward Fill
df_back_fill = df.fillna(method='bfill')

# Interpolation
df_interpolate = df.interpolate()

# Mean Fill
df_mean_fill = df.fillna(df.mean(numeric_only=True))


# STEP 5: Display results
print("\n--- Forward Fill ---")
display(df_forward_fill)

print("\n--- Backward Fill ---")
display(df_back_fill)

print("\n--- Interpolation ---")
display(df_interpolate)

print("\n--- Mean Fill ---")
display(df_mean_fill)

# STEP 6: Save EACH dataframe as CSV (optional but useful for CA)
df_forward_fill.to_csv("forward_fill.csv", index=False)
df_back_fill.to_csv("backward_fill.csv", index=False)
df_interpolate.to_csv("interpolated.csv", index=False)
df_mean_fill.to_csv("mean_fill.csv", index=False)

print("\nAll cleaned datasets saved as CSV files!")

Saving sensor_log.csv to sensor_log.csv
Original Data:

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00           24.5          55.2       3.70
1  2025-10-01 08:00:10           24.7          55.0       3.69
2  2025-10-01 08:00:20           24.6          55.1        NaN
3  2025-10-01 08:00:30            NaN          54.9       3.68
4  2025-10-01 08:01:00           24.9          54.8       3.68
5  2025-10-01 08:02:15           25.1           NaN       3.67
6  2025-10-01 08:03:00           25.3          54.7       3.67
7  2025-10-01 08:05:30           25.5          54.9       3.65
8  2025-10-01 08:08:00            NaN          55.0       3.64
9  2025-10-01 08:10:00           26.0          55.1       3.63

Missing values in each column:
timestamp        0
temperature_c    2
humidity_pct     1
voltage_v        1
dtype: int64

--- Forward Fill ---

/tmp/ipython-input-1012197610.py:17: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_forward_fill = df.fillna(method='ffill')
/tmp/ipython-input-1012197610.py:20: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_back_fill = df.fillna(method='bfill')
/tmp/ipython-input-1012197610.py:23: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolate = df.interpolate()

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00           24.5          55.2       3.70
1  2025-10-01 08:00:10           24.7          55.0       3.69
2  2025-10-01 08:00:20           24.6          55.1       3.69
3  2025-10-01 08:00:30           24.6          54.9       3.68
4  2025-10-01 08:01:00           24.9          54.8       3.68
5  2025-10-01 08:02:15           25.1          54.8       3.67
6  2025-10-01 08:03:00           25.3          54.7       3.67
7  2025-10-01 08:05:30           25.5          54.9       3.65
8  2025-10-01 08:08:00           25.5          55.0       3.64
9  2025-10-01 08:10:00           26.0          55.1       3.63

--- Backward Fill ---

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00           24.5          55.2       3.70
1  2025-10-01 08:00:10           24.7          55.0       3.69
2  2025-10-01 08:00:20           24.6          55.1       3.68
3  2025-10-01 08:00:30           24.9          54.9       3.68
4  2025-10-01 08:01:00           24.9          54.8       3.68
5  2025-10-01 08:02:15           25.1          54.7       3.67
6  2025-10-01 08:03:00           25.3          54.7       3.67
7  2025-10-01 08:05:30           25.5          54.9       3.65
8  2025-10-01 08:08:00           26.0          55.0       3.64
9  2025-10-01 08:10:00           26.0          55.1       3.63

--- Interpolation ---

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00          24.50         55.20      3.700
1  2025-10-01 08:00:10          24.70         55.00      3.690
2  2025-10-01 08:00:20          24.60         55.10      3.685
3  2025-10-01 08:00:30          24.75         54.90      3.680
4  2025-10-01 08:01:00          24.90         54.80      3.680
5  2025-10-01 08:02:15          25.10         54.75      3.670
6  2025-10-01 08:03:00          25.30         54.70      3.670
7  2025-10-01 08:05:30          25.50         54.90      3.650
8  2025-10-01 08:08:00          25.75         55.00      3.640
9  2025-10-01 08:10:00          26.00         55.10      3.630

--- Mean Fill ---

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00         24.500     55.200000   3.700000
1  2025-10-01 08:00:10         24.700     55.000000   3.690000
2  2025-10-01 08:00:20         24.600     55.100000   3.667778
3  2025-10-01 08:00:30         25.075     54.900000   3.680000
4  2025-10-01 08:01:00         24.900     54.800000   3.680000
5  2025-10-01 08:02:15         25.100     54.966667   3.670000
6  2025-10-01 08:03:00         25.300     54.700000   3.670000
7  2025-10-01 08:05:30         25.500     54.900000   3.650000
8  2025-10-01 08:08:00         25.075     55.000000   3.640000
9  2025-10-01 08:10:00         26.000     55.100000   3.630000

All cleaned datasets saved as CSV files!

Downloading all csv files

In [2]:
from google.colab import files
files.download('forward_fill.csv')
files.download('backward_fill.csv')
files.download('interpolated.csv')
files.download('mean_fill.csv')

In [3]:
df_interpolate.describe()

       temperature_c  humidity_pct  voltage_v
count       10.00000     10.000000  10.000000
mean        25.11000     54.945000   3.669500
std          0.51251      0.164063   0.022663
min         24.50000     54.700000   3.630000
25%         24.71250     54.825000   3.655000
50%         25.00000     54.950000   3.675000
75%         25.45000     55.075000   3.683750
max         26.00000     55.200000   3.700000

Exercise 1

In [4]:
# Rows where temperature is missing
temp_missing_df = df[df["temperature_c"].isna()]

# Rows where humidity is missing
humidity_missing_df = df[df["humidity_pct"].isna()]

# (Optional) only the temperature series with missing rows
temp_missing_series = df.loc[df["temperature_c"].isna(), "temperature_c"]

# Percentage of missing values per column
missing_counts = df.isna().sum()
missing_percent = missing_counts / len(df) * 100

print("Missing % by column:")
print(missing_percent)

print("\nColumn with highest missing %:")
print(missing_percent.idxmax(), "→", missing_percent.max(), "%")

Missing % by column:
timestamp         0.0
temperature_c    20.0
humidity_pct     10.0
voltage_v        10.0
dtype: float64

Column with highest missing %:
temperature_c → 20.0 %

Exercise 2

In [6]:
# Copy of the original df
df_median = df.copy()

# Select only numeric columns
numeric_cols = df_median.select_dtypes(include="number").columns

# Median-based imputation
df_median[numeric_cols] = df_median[numeric_cols].fillna(
    df_median[numeric_cols].median()
)

# ---------- CREATE df_mean (this was missing) ----------
df_mean = df.copy()
df_mean[numeric_cols] = df_mean[numeric_cols].fillna(
    df_mean[numeric_cols].mean()
)
# -------------------------------------------------------

# Compare results
print("Mean-based imputation (df_mean):")
display(df_mean[numeric_cols].describe())

print("\nMedian-based imputation (df_median):")
display(df_median[numeric_cols].describe())

Mean-based imputation (df_mean):

       temperature_c  humidity_pct  voltage_v
count      10.000000     10.000000  10.000000
mean       25.075000     54.966667   3.667778
std         0.449073      0.149071   0.021999
min        24.500000     54.700000   3.630000
25%        24.750000     54.900000   3.654444
50%        25.075000     54.983333   3.670000
75%        25.250000     55.075000   3.680000
max        26.000000     55.200000   3.700000

Median-based imputation (df_median):

       temperature_c  humidity_pct  voltage_v
count      10.000000     10.000000   10.00000
mean       25.060000     54.970000    3.66800
std         0.450185      0.149443    0.02201
min        24.500000     54.700000    3.63000
25%        24.750000     54.900000    3.65500
50%        25.000000     55.000000    3.67000
75%        25.250000     55.075000    3.68000
max        26.000000     55.200000    3.70000

Exercise 3

In [9]:
import pandas as pd

# ✅ 1. Start from the original dataframe df
# If you already have df from sensor_log.csv, no need to reload it.
# df = pd.read_csv("sensor_log.csv")

# For this exercise, we'll treat the existing index as the time order
df_ts = df.copy().sort_index()

# ✅ 2. Create forward-fill and interpolation versions
df_ts_ffill = df_ts.ffill()          # Forward fill
df_ts_interp = df_ts.interpolate()   # Interpolation

# ✅ 3. Choose a small time range safely (e.g. first 10 rows or fewer)
end = min(10, len(df_ts))   # if you have fewer than 10 rows, it won't break

# Side-by-side comparison for temperature_c (you can also do for humidity, voltage)
comparison_temp = pd.DataFrame({
    "original_temp": df_ts["temperature_c"].iloc[0:end],
    "ffill_temp":    df_ts_ffill["temperature_c"].iloc[0:end],
    "interp_temp":   df_ts_interp["temperature_c"].iloc[0:end],
})

print("Temperature comparison (original vs forward fill vs interpolation):")
print(comparison_temp)

# ✅ Optional: also compare humidity and voltage the same way
comparison_hum = pd.DataFrame({
    "original_hum": df_ts["humidity_pct"].iloc[0:end],
    "ffill_hum":    df_ts_ffill["humidity_pct"].iloc[0:end],
    "interp_hum":   df_ts_interp["humidity_pct"].iloc[0:end],
})

print("\nHumidity comparison:")
print(comparison_hum)

comparison_volt = pd.DataFrame({
    "original_volt": df_ts["voltage_v"].iloc[0:end],
    "ffill_volt":    df_ts_ffill["voltage_v"].iloc[0:end],
    "interp_volt":   df_ts_interp["voltage_v"].iloc[0:end],
})

print("\nVoltage comparison:")
print(comparison_volt)

Temperature comparison (original vs forward fill vs interpolation):
   original_temp  ffill_temp  interp_temp
0           24.5        24.5        24.50
1           24.7        24.7        24.70
2           24.6        24.6        24.60
3            NaN        24.6        24.75
4           24.9        24.9        24.90
5           25.1        25.1        25.10
6           25.3        25.3        25.30
7           25.5        25.5        25.50
8            NaN        25.5        25.75
9           26.0        26.0        26.00

Humidity comparison:
   original_hum  ffill_hum  interp_hum
0          55.2       55.2       55.20
1          55.0       55.0       55.00
2          55.1       55.1       55.10
3          54.9       54.9       54.90
4          54.8       54.8       54.80
5           NaN       54.8       54.75
6          54.7       54.7       54.70
7          54.9       54.9       54.90
8          55.0       55.0       55.00
9          55.1       55.1       55.10

Voltage comparison:
   original_volt  ffill_volt  interp_volt
0           3.70        3.70        3.700
1           3.69        3.69        3.690
2            NaN        3.69        3.685
3           3.68        3.68        3.680
4           3.68        3.68        3.680
5           3.67        3.67        3.670
6           3.67        3.67        3.670
7           3.65        3.65        3.650
8           3.64        3.64        3.640
9           3.63        3.63        3.630