In [ ]:
# STEP 1: Upload dataset
from google.colab import files
uploaded = files.upload()   # Select sensor_log.csv manually

# STEP 2: Load data
import pandas as pd
df = pd.read_csv("sensor_log.csv")  # filename only!
print("Original Data:")
display(df)

# STEP 3: Check missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# STEP 4: Create 4 different versions
# Forward Fill
df_forward_fill = df.fillna(method='ffill')

# Backward Fill
df_back_fill = df.fillna(method='bfill')

# Interpolation
df_interpolate = df.interpolate()

# Mean Fill
df_mean_fill = df.fillna(df.mean(numeric_only=True))


# STEP 5: Display results
print("\n--- Forward Fill ---")
display(df_forward_fill)

print("\n--- Backward Fill ---")
display(df_back_fill)

print("\n--- Interpolation ---")
display(df_interpolate)

print("\n--- Mean Fill ---")
display(df_mean_fill)

# STEP 6: Save EACH dataframe as CSV (optional but useful for CA)
df_forward_fill.to_csv("forward_fill.csv", index=False)
df_back_fill.to_csv("backward_fill.csv", index=False)
df_interpolate.to_csv("interpolated.csv", index=False)
df_mean_fill.to_csv("mean_fill.csv", index=False)

print("\nAll cleaned datasets saved as CSV files!")

Saving sensor_log.csv to sensor_log.csv
Original Data:

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00           24.5          55.2       3.70
1  2025-10-01 08:00:10           24.7          55.0       3.69
2  2025-10-01 08:00:20           24.6          55.1        NaN
3  2025-10-01 08:00:30            NaN          54.9       3.68
4  2025-10-01 08:01:00           24.9          54.8       3.68
5  2025-10-01 08:02:15           25.1           NaN       3.67
6  2025-10-01 08:03:00           25.3          54.7       3.67
7  2025-10-01 08:05:30           25.5          54.9       3.65
8  2025-10-01 08:08:00            NaN          55.0       3.64
9  2025-10-01 08:10:00           26.0          55.1       3.63

Missing values in each column:
timestamp        0
temperature_c    2
humidity_pct     1
voltage_v        1
dtype: int64

--- Forward Fill ---

/tmp/ipython-input-1012197610.py:17: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_forward_fill = df.fillna(method='ffill')
/tmp/ipython-input-1012197610.py:20: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_back_fill = df.fillna(method='bfill')
/tmp/ipython-input-1012197610.py:23: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolate = df.interpolate()

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00           24.5          55.2       3.70
1  2025-10-01 08:00:10           24.7          55.0       3.69
2  2025-10-01 08:00:20           24.6          55.1       3.69
3  2025-10-01 08:00:30           24.6          54.9       3.68
4  2025-10-01 08:01:00           24.9          54.8       3.68
5  2025-10-01 08:02:15           25.1          54.8       3.67
6  2025-10-01 08:03:00           25.3          54.7       3.67
7  2025-10-01 08:05:30           25.5          54.9       3.65
8  2025-10-01 08:08:00           25.5          55.0       3.64
9  2025-10-01 08:10:00           26.0          55.1       3.63

--- Backward Fill ---

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00           24.5          55.2       3.70
1  2025-10-01 08:00:10           24.7          55.0       3.69
2  2025-10-01 08:00:20           24.6          55.1       3.68
3  2025-10-01 08:00:30           24.9          54.9       3.68
4  2025-10-01 08:01:00           24.9          54.8       3.68
5  2025-10-01 08:02:15           25.1          54.7       3.67
6  2025-10-01 08:03:00           25.3          54.7       3.67
7  2025-10-01 08:05:30           25.5          54.9       3.65
8  2025-10-01 08:08:00           26.0          55.0       3.64
9  2025-10-01 08:10:00           26.0          55.1       3.63

--- Interpolation ---

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00          24.50         55.20      3.700
1  2025-10-01 08:00:10          24.70         55.00      3.690
2  2025-10-01 08:00:20          24.60         55.10      3.685
3  2025-10-01 08:00:30          24.75         54.90      3.680
4  2025-10-01 08:01:00          24.90         54.80      3.680
5  2025-10-01 08:02:15          25.10         54.75      3.670
6  2025-10-01 08:03:00          25.30         54.70      3.670
7  2025-10-01 08:05:30          25.50         54.90      3.650
8  2025-10-01 08:08:00          25.75         55.00      3.640
9  2025-10-01 08:10:00          26.00         55.10      3.630

--- Mean Fill ---

             timestamp  temperature_c  humidity_pct  voltage_v
0  2025-10-01 08:00:00         24.500     55.200000   3.700000
1  2025-10-01 08:00:10         24.700     55.000000   3.690000
2  2025-10-01 08:00:20         24.600     55.100000   3.667778
3  2025-10-01 08:00:30         25.075     54.900000   3.680000
4  2025-10-01 08:01:00         24.900     54.800000   3.680000
5  2025-10-01 08:02:15         25.100     54.966667   3.670000
6  2025-10-01 08:03:00         25.300     54.700000   3.670000
7  2025-10-01 08:05:30         25.500     54.900000   3.650000
8  2025-10-01 08:08:00         25.075     55.000000   3.640000
9  2025-10-01 08:10:00         26.000     55.100000   3.630000

All cleaned datasets saved as CSV files!

Downloading all csv files

In [ ]:
from google.colab import files
files.download('forward_fill.csv')
files.download('backward_fill.csv')
files.download('interpolated.csv')
files.download('mean_fill.csv')

In [ ]:
df_interpolate.describe()

       temperature_c  humidity_pct  voltage_v
count       10.00000     10.000000  10.000000
mean        25.11000     54.945000   3.669500
std          0.51251      0.164063   0.022663
min         24.50000     54.700000   3.630000
25%         24.71250     54.825000   3.655000
50%         25.00000     54.950000   3.675000
75%         25.45000     55.075000   3.683750
max         26.00000     55.200000   3.700000

from matplotlib import pyplot as plt
_df_0['temperature_c'].plot(kind='hist', bins=20, title='temperature_c')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['humidity_pct'].plot(kind='hist', bins=20, title='humidity_pct')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['voltage_v'].plot(kind='hist', bins=20, title='voltage_v')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='temperature_c', y='humidity_pct', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='humidity_pct', y='voltage_v', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5['temperature_c'].plot(kind='line', figsize=(8, 4), title='temperature_c')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['humidity_pct'].plot(kind='line', figsize=(8, 4), title='humidity_pct')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['voltage_v'].plot(kind='line', figsize=(8, 4), title='voltage_v')
plt.gca().spines[['top', 'right']].set_visible(False)